INSERT INTO ads (
    id,
    title,
    price,
    price_value,
    location,
    description,
    date_posted,
    url,
    image_url,
    ad_type,
    brand,
    scraped_at,
    model_ai,
    embedding,
    source,
    external_id,
    posted_at,
    seller_info,
    metadata
  )
VALUES (
    'id:text',
    'title:text',
    'price:text',
    'price_value:double precision',
    'location:text',
    'description:text',
    'date_posted:text',
    'url:text',
    'image_url:text',
    'ad_type:text',
    'brand:text',
    'scraped_at:timestamp with time zone',
    'model_ai:text',
    'embedding:text',
    'source:text',
    'external_id:text',
    'posted_at:timestamp with time zone',
    'seller_info:jsonb',
    'metadata:jsonb'
  );